#!/bin/bash


main_h="
#ifndef MAIN_H
#define MAIN_H



#endif
"




main_cpp="
#include \"func{i}.h\"
#include \"main{i}.h\"

int main()
{
  printHello();  

  return 0;
}
"


func_h="
#ifndef FUNC_H
#define FUNC_H


void printHello();


#endif
"


func_cpp="
#include <iostream>


#include \"func{i}.h\"

void printHello()
{
  std::cout << \"Hello world ${i}\" << std::endl;
}
"

echo > user.mk

for i in $(seq 1 10000); do
  echo -n $i " "

  echo "${func_h}"    | sed 's|{i}|'${i}'|g' > func${i}.h
  echo "${func_cpp}"  | sed 's|{i}|'${i}'|g' > func${i}.cpp
  echo "${main_h}"    | sed 's|{i}|'${i}'|g' > main${i}.h
  echo "${main_cpp}"  | sed 's|{i}|'${i}'|g' > main${i}.cpp  
  
  echo "
TARGETS += main${i}
main${i}.SRCS := main${i}.cpp func${i}.cpp
main${i}.TYPE := executable

        " >> user.mk 
done

