ifndef sources
$(error please pass sources)
endif

.SUFFIXES:

objects    := $(sources:.cpp=.o)
deps_files := $(patsubst %.cpp,%.cpp.d,$(sources))


$(executable): $(objects)
	echo main: $$(cat $(deps_files) | grep -Po "\w+\.h" | sort -u | tr '\n' ' ') > main.d
	g++ $^ -o $@

%.o: %.cpp %.cpp.d
	g++ -c $<

%.cpp.d: %.cpp
	g++ -MM -MG $< > $<.d

$(generate_headers):%.h:
	./$($@_generator) $* > $@

$(deps_files):$(generate_headers)

-include  $(deps_files)
