ifndef sources
$(error please pass sources)
endif

.SUFFIXES:

objects    := $(sources:.cpp=.o)
deps_files := $(patsubst %.cpp,%.cpp.d,$(sources))


$(executable): $(objects) 
	echo main: $$(cat $(deps_files) | grep -Po "[\w]+\.h" | sort | uniq | tr '\n' ' ') > main.d
	g++ $^ -o $@

%.o: %.cpp %.cpp.d
	g++ -c $<

%.cpp.d: %.cpp
	g++ -MM -MG $< > $<.d

$(gen_headers):%.h:
	./generate_header $* > $@

-include  $(deps_files)

